// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: grpc_control.proto

package grpc_control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_AddDataSource_FullMethodName    = "/grpc_control.ControlService/AddDataSource"
	ControlService_RemoveDataSource_FullMethodName = "/grpc_control.ControlService/RemoveDataSource"
	ControlService_StartBroker_FullMethodName      = "/grpc_control.ControlService/StartBroker"
	ControlService_StopBroker_FullMethodName       = "/grpc_control.ControlService/StopBroker"
	ControlService_ListBrokers_FullMethodName      = "/grpc_control.ControlService/ListBrokers"
	ControlService_AddSymbols_FullMethodName       = "/grpc_control.ControlService/AddSymbols"
	ControlService_AddSymbolsAll_FullMethodName    = "/grpc_control.ControlService/AddSymbolsAll"
	ControlService_RemoveSymbols_FullMethodName    = "/grpc_control.ControlService/RemoveSymbols"
	ControlService_RemoveSymbolsAll_FullMethodName = "/grpc_control.ControlService/RemoveSymbolsAll"
	ControlService_GetBrokerStatus_FullMethodName  = "/grpc_control.ControlService/GetBrokerStatus"
	ControlService_HealthCheck_FullMethodName      = "/grpc_control.ControlService/HealthCheck"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	// Data Source Management
	AddDataSource(ctx context.Context, in *AddDataSourceRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	RemoveDataSource(ctx context.Context, in *RemoveDataSourceRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	// Broker Management
	StartBroker(ctx context.Context, in *StartBrokerRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	StopBroker(ctx context.Context, in *StopBrokerRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	ListBrokers(ctx context.Context, in *ListBrokersRequest, opts ...grpc.CallOption) (*ListBrokersResponse, error)
	// Symbol Management
	AddSymbols(ctx context.Context, in *AddSymbolsRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	AddSymbolsAll(ctx context.Context, in *AddSymbolsAllRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	RemoveSymbols(ctx context.Context, in *RemoveSymbolsRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	RemoveSymbolsAll(ctx context.Context, in *RemoveSymbolsAllRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	// Broker Status
	GetBrokerStatus(ctx context.Context, in *GetBrokerStatusRequest, opts ...grpc.CallOption) (*BrokerStatusResponse, error)
	// Health Check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) AddDataSource(ctx context.Context, in *AddDataSourceRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ControlService_AddDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RemoveDataSource(ctx context.Context, in *RemoveDataSourceRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ControlService_RemoveDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) StartBroker(ctx context.Context, in *StartBrokerRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ControlService_StartBroker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) StopBroker(ctx context.Context, in *StopBrokerRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ControlService_StopBroker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListBrokers(ctx context.Context, in *ListBrokersRequest, opts ...grpc.CallOption) (*ListBrokersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBrokersResponse)
	err := c.cc.Invoke(ctx, ControlService_ListBrokers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) AddSymbols(ctx context.Context, in *AddSymbolsRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ControlService_AddSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) AddSymbolsAll(ctx context.Context, in *AddSymbolsAllRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ControlService_AddSymbolsAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RemoveSymbols(ctx context.Context, in *RemoveSymbolsRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ControlService_RemoveSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RemoveSymbolsAll(ctx context.Context, in *RemoveSymbolsAllRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ControlService_RemoveSymbolsAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetBrokerStatus(ctx context.Context, in *GetBrokerStatusRequest, opts ...grpc.CallOption) (*BrokerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrokerStatusResponse)
	err := c.cc.Invoke(ctx, ControlService_GetBrokerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ControlService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	// Data Source Management
	AddDataSource(context.Context, *AddDataSourceRequest) (*ControlResponse, error)
	RemoveDataSource(context.Context, *RemoveDataSourceRequest) (*ControlResponse, error)
	// Broker Management
	StartBroker(context.Context, *StartBrokerRequest) (*ControlResponse, error)
	StopBroker(context.Context, *StopBrokerRequest) (*ControlResponse, error)
	ListBrokers(context.Context, *ListBrokersRequest) (*ListBrokersResponse, error)
	// Symbol Management
	AddSymbols(context.Context, *AddSymbolsRequest) (*ControlResponse, error)
	AddSymbolsAll(context.Context, *AddSymbolsAllRequest) (*ControlResponse, error)
	RemoveSymbols(context.Context, *RemoveSymbolsRequest) (*ControlResponse, error)
	RemoveSymbolsAll(context.Context, *RemoveSymbolsAllRequest) (*ControlResponse, error)
	// Broker Status
	GetBrokerStatus(context.Context, *GetBrokerStatusRequest) (*BrokerStatusResponse, error)
	// Health Check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) AddDataSource(context.Context, *AddDataSourceRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDataSource not implemented")
}
func (UnimplementedControlServiceServer) RemoveDataSource(context.Context, *RemoveDataSourceRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDataSource not implemented")
}
func (UnimplementedControlServiceServer) StartBroker(context.Context, *StartBrokerRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBroker not implemented")
}
func (UnimplementedControlServiceServer) StopBroker(context.Context, *StopBrokerRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopBroker not implemented")
}
func (UnimplementedControlServiceServer) ListBrokers(context.Context, *ListBrokersRequest) (*ListBrokersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBrokers not implemented")
}
func (UnimplementedControlServiceServer) AddSymbols(context.Context, *AddSymbolsRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSymbols not implemented")
}
func (UnimplementedControlServiceServer) AddSymbolsAll(context.Context, *AddSymbolsAllRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSymbolsAll not implemented")
}
func (UnimplementedControlServiceServer) RemoveSymbols(context.Context, *RemoveSymbolsRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSymbols not implemented")
}
func (UnimplementedControlServiceServer) RemoveSymbolsAll(context.Context, *RemoveSymbolsAllRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSymbolsAll not implemented")
}
func (UnimplementedControlServiceServer) GetBrokerStatus(context.Context, *GetBrokerStatusRequest) (*BrokerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBrokerStatus not implemented")
}
func (UnimplementedControlServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_AddDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).AddDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_AddDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).AddDataSource(ctx, req.(*AddDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RemoveDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RemoveDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RemoveDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RemoveDataSource(ctx, req.(*RemoveDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_StartBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).StartBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_StartBroker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).StartBroker(ctx, req.(*StartBrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_StopBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopBrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).StopBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_StopBroker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).StopBroker(ctx, req.(*StopBrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListBrokers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBrokersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListBrokers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListBrokers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListBrokers(ctx, req.(*ListBrokersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_AddSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).AddSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_AddSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).AddSymbols(ctx, req.(*AddSymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_AddSymbolsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSymbolsAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).AddSymbolsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_AddSymbolsAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).AddSymbolsAll(ctx, req.(*AddSymbolsAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RemoveSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RemoveSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RemoveSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RemoveSymbols(ctx, req.(*RemoveSymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RemoveSymbolsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSymbolsAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RemoveSymbolsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RemoveSymbolsAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RemoveSymbolsAll(ctx, req.(*RemoveSymbolsAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetBrokerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrokerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetBrokerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetBrokerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetBrokerStatus(ctx, req.(*GetBrokerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_control.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDataSource",
			Handler:    _ControlService_AddDataSource_Handler,
		},
		{
			MethodName: "RemoveDataSource",
			Handler:    _ControlService_RemoveDataSource_Handler,
		},
		{
			MethodName: "StartBroker",
			Handler:    _ControlService_StartBroker_Handler,
		},
		{
			MethodName: "StopBroker",
			Handler:    _ControlService_StopBroker_Handler,
		},
		{
			MethodName: "ListBrokers",
			Handler:    _ControlService_ListBrokers_Handler,
		},
		{
			MethodName: "AddSymbols",
			Handler:    _ControlService_AddSymbols_Handler,
		},
		{
			MethodName: "AddSymbolsAll",
			Handler:    _ControlService_AddSymbolsAll_Handler,
		},
		{
			MethodName: "RemoveSymbols",
			Handler:    _ControlService_RemoveSymbols_Handler,
		},
		{
			MethodName: "RemoveSymbolsAll",
			Handler:    _ControlService_RemoveSymbolsAll_Handler,
		},
		{
			MethodName: "GetBrokerStatus",
			Handler:    _ControlService_GetBrokerStatus_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ControlService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_control.proto",
}
