// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: grpc_control.proto

package grpc_control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_grpc_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ControlResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type AddDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceType    string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Symbols       []string               `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDataSourceRequest) Reset() {
	*x = AddDataSourceRequest{}
	mi := &file_grpc_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataSourceRequest) ProtoMessage() {}

func (x *AddDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataSourceRequest.ProtoReflect.Descriptor instead.
func (*AddDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{1}
}

func (x *AddDataSourceRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *AddDataSourceRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AddDataSourceRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *AddDataSourceRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AddDataSourceRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type RemoveDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDataSourceRequest) Reset() {
	*x = RemoveDataSourceRequest{}
	mi := &file_grpc_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDataSourceRequest) ProtoMessage() {}

func (x *RemoveDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDataSourceRequest.ProtoReflect.Descriptor instead.
func (*RemoveDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveDataSourceRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

type ModifyDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceType    string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Symbols       []string               `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyDataSourceRequest) Reset() {
	*x = ModifyDataSourceRequest{}
	mi := &file_grpc_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyDataSourceRequest) ProtoMessage() {}

func (x *ModifyDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyDataSourceRequest.ProtoReflect.Descriptor instead.
func (*ModifyDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyDataSourceRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ModifyDataSourceRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ModifyDataSourceRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *ModifyDataSourceRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ModifyDataSourceRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type StartBrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerName    string                 `protobuf:"bytes,1,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	BrokerType    string                 `protobuf:"bytes,2,opt,name=broker_type,json=brokerType,proto3" json:"broker_type,omitempty"`
	Symbols       []string               `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBrokerRequest) Reset() {
	*x = StartBrokerRequest{}
	mi := &file_grpc_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBrokerRequest) ProtoMessage() {}

func (x *StartBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBrokerRequest.ProtoReflect.Descriptor instead.
func (*StartBrokerRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{4}
}

func (x *StartBrokerRequest) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *StartBrokerRequest) GetBrokerType() string {
	if x != nil {
		return x.BrokerType
	}
	return ""
}

func (x *StartBrokerRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *StartBrokerRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *StartBrokerRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type StopBrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerName    string                 `protobuf:"bytes,1,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopBrokerRequest) Reset() {
	*x = StopBrokerRequest{}
	mi := &file_grpc_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBrokerRequest) ProtoMessage() {}

func (x *StopBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBrokerRequest.ProtoReflect.Descriptor instead.
func (*StopBrokerRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{5}
}

func (x *StopBrokerRequest) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

type GetBrokerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerName    string                 `protobuf:"bytes,1,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrokerStatusRequest) Reset() {
	*x = GetBrokerStatusRequest{}
	mi := &file_grpc_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrokerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrokerStatusRequest) ProtoMessage() {}

func (x *GetBrokerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrokerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBrokerStatusRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{6}
}

func (x *GetBrokerStatusRequest) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

type BrokerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerName    string                 `protobuf:"bytes,1,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Symbols       []string               `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	BrokerType    string                 `protobuf:"bytes,4,opt,name=broker_type,json=brokerType,proto3" json:"broker_type,omitempty"`
	StatusMessage string                 `protobuf:"bytes,5,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	ApiKey        string                 `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,7,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerStatusResponse) Reset() {
	*x = BrokerStatusResponse{}
	mi := &file_grpc_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerStatusResponse) ProtoMessage() {}

func (x *BrokerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerStatusResponse.ProtoReflect.Descriptor instead.
func (*BrokerStatusResponse) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{7}
}

func (x *BrokerStatusResponse) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *BrokerStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *BrokerStatusResponse) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *BrokerStatusResponse) GetBrokerType() string {
	if x != nil {
		return x.BrokerType
	}
	return ""
}

func (x *BrokerStatusResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *BrokerStatusResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *BrokerStatusResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type BrokerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerName    string                 `protobuf:"bytes,1,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	BrokerType    string                 `protobuf:"bytes,2,opt,name=broker_type,json=brokerType,proto3" json:"broker_type,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Running       bool                   `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	Symbols       []string               `protobuf:"bytes,5,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerInfo) Reset() {
	*x = BrokerInfo{}
	mi := &file_grpc_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerInfo) ProtoMessage() {}

func (x *BrokerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerInfo.ProtoReflect.Descriptor instead.
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{8}
}

func (x *BrokerInfo) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *BrokerInfo) GetBrokerType() string {
	if x != nil {
		return x.BrokerType
	}
	return ""
}

func (x *BrokerInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *BrokerInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *BrokerInfo) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *BrokerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListBrokersRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncludeAvailable bool                   `protobuf:"varint,1,opt,name=include_available,json=includeAvailable,proto3" json:"include_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListBrokersRequest) Reset() {
	*x = ListBrokersRequest{}
	mi := &file_grpc_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrokersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrokersRequest) ProtoMessage() {}

func (x *ListBrokersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrokersRequest.ProtoReflect.Descriptor instead.
func (*ListBrokersRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{9}
}

func (x *ListBrokersRequest) GetIncludeAvailable() bool {
	if x != nil {
		return x.IncludeAvailable
	}
	return false
}

type ListBrokersResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunningBrokers   []*BrokerInfo          `protobuf:"bytes,1,rep,name=running_brokers,json=runningBrokers,proto3" json:"running_brokers,omitempty"`
	AvailableBrokers []*BrokerInfo          `protobuf:"bytes,2,rep,name=available_brokers,json=availableBrokers,proto3" json:"available_brokers,omitempty"`
	TotalRunning     int32                  `protobuf:"varint,3,opt,name=total_running,json=totalRunning,proto3" json:"total_running,omitempty"`
	TotalAvailable   int32                  `protobuf:"varint,4,opt,name=total_available,json=totalAvailable,proto3" json:"total_available,omitempty"`
	Timestamp        int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListBrokersResponse) Reset() {
	*x = ListBrokersResponse{}
	mi := &file_grpc_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrokersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrokersResponse) ProtoMessage() {}

func (x *ListBrokersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrokersResponse.ProtoReflect.Descriptor instead.
func (*ListBrokersResponse) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{10}
}

func (x *ListBrokersResponse) GetRunningBrokers() []*BrokerInfo {
	if x != nil {
		return x.RunningBrokers
	}
	return nil
}

func (x *ListBrokersResponse) GetAvailableBrokers() []*BrokerInfo {
	if x != nil {
		return x.AvailableBrokers
	}
	return nil
}

func (x *ListBrokersResponse) GetTotalRunning() int32 {
	if x != nil {
		return x.TotalRunning
	}
	return 0
}

func (x *ListBrokersResponse) GetTotalAvailable() int32 {
	if x != nil {
		return x.TotalAvailable
	}
	return 0
}

func (x *ListBrokersResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AvailableBrokersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableBrokersRequest) Reset() {
	*x = AvailableBrokersRequest{}
	mi := &file_grpc_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableBrokersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableBrokersRequest) ProtoMessage() {}

func (x *AvailableBrokersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableBrokersRequest.ProtoReflect.Descriptor instead.
func (*AvailableBrokersRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{11}
}

type AvailableBrokersResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AvailableBrokers []*BrokerInfo          `protobuf:"bytes,1,rep,name=available_brokers,json=availableBrokers,proto3" json:"available_brokers,omitempty"`
	TotalCount       int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Timestamp        int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AvailableBrokersResponse) Reset() {
	*x = AvailableBrokersResponse{}
	mi := &file_grpc_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableBrokersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableBrokersResponse) ProtoMessage() {}

func (x *AvailableBrokersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableBrokersResponse.ProtoReflect.Descriptor instead.
func (*AvailableBrokersResponse) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{12}
}

func (x *AvailableBrokersResponse) GetAvailableBrokers() []*BrokerInfo {
	if x != nil {
		return x.AvailableBrokers
	}
	return nil
}

func (x *AvailableBrokersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *AvailableBrokersResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AddSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerName    string                 `protobuf:"bytes,1,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSymbolsRequest) Reset() {
	*x = AddSymbolsRequest{}
	mi := &file_grpc_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSymbolsRequest) ProtoMessage() {}

func (x *AddSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSymbolsRequest.ProtoReflect.Descriptor instead.
func (*AddSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{13}
}

func (x *AddSymbolsRequest) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *AddSymbolsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type AddSymbolsAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSymbolsAllRequest) Reset() {
	*x = AddSymbolsAllRequest{}
	mi := &file_grpc_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSymbolsAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSymbolsAllRequest) ProtoMessage() {}

func (x *AddSymbolsAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSymbolsAllRequest.ProtoReflect.Descriptor instead.
func (*AddSymbolsAllRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{14}
}

func (x *AddSymbolsAllRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type RemoveSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerName    string                 `protobuf:"bytes,1,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSymbolsRequest) Reset() {
	*x = RemoveSymbolsRequest{}
	mi := &file_grpc_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSymbolsRequest) ProtoMessage() {}

func (x *RemoveSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSymbolsRequest.ProtoReflect.Descriptor instead.
func (*RemoveSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveSymbolsRequest) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *RemoveSymbolsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type RemoveSymbolsAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSymbolsAllRequest) Reset() {
	*x = RemoveSymbolsAllRequest{}
	mi := &file_grpc_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSymbolsAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSymbolsAllRequest) ProtoMessage() {}

func (x *RemoveSymbolsAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSymbolsAllRequest.ProtoReflect.Descriptor instead.
func (*RemoveSymbolsAllRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveSymbolsAllRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_grpc_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{17}
}

func (x *HealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_grpc_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_grpc_control_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_grpc_control_proto protoreflect.FileDescriptor

const file_grpc_control_proto_rawDesc = "" +
	"\n" +
	"\x12grpc_control.proto\x12\fgrpc_control\"\x82\x01\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\xa7\x01\n" +
	"\x14AddDataSourceRequest\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x18\n" +
	"\asymbols\x18\x03 \x03(\tR\asymbols\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\":\n" +
	"\x17RemoveDataSourceRequest\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\"\xaa\x01\n" +
	"\x17ModifyDataSourceRequest\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x18\n" +
	"\asymbols\x18\x03 \x03(\tR\asymbols\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\"\xa5\x01\n" +
	"\x12StartBrokerRequest\x12\x1f\n" +
	"\vbroker_name\x18\x01 \x01(\tR\n" +
	"brokerName\x12\x1f\n" +
	"\vbroker_type\x18\x02 \x01(\tR\n" +
	"brokerType\x12\x18\n" +
	"\asymbols\x18\x03 \x03(\tR\asymbols\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\"4\n" +
	"\x11StopBrokerRequest\x12\x1f\n" +
	"\vbroker_name\x18\x01 \x01(\tR\n" +
	"brokerName\"9\n" +
	"\x16GetBrokerStatusRequest\x12\x1f\n" +
	"\vbroker_name\x18\x01 \x01(\tR\n" +
	"brokerName\"\xe8\x01\n" +
	"\x14BrokerStatusResponse\x12\x1f\n" +
	"\vbroker_name\x18\x01 \x01(\tR\n" +
	"brokerName\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x18\n" +
	"\asymbols\x18\x03 \x03(\tR\asymbols\x12\x1f\n" +
	"\vbroker_type\x18\x04 \x01(\tR\n" +
	"brokerType\x12%\n" +
	"\x0estatus_message\x18\x05 \x01(\tR\rstatusMessage\x12\x17\n" +
	"\aapi_key\x18\x06 \x01(\tR\x06apiKey\x12\x1a\n" +
	"\bendpoint\x18\a \x01(\tR\bendpoint\"\xb6\x01\n" +
	"\n" +
	"BrokerInfo\x12\x1f\n" +
	"\vbroker_name\x18\x01 \x01(\tR\n" +
	"brokerName\x12\x1f\n" +
	"\vbroker_type\x18\x02 \x01(\tR\n" +
	"brokerType\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x18\n" +
	"\arunning\x18\x04 \x01(\bR\arunning\x12\x18\n" +
	"\asymbols\x18\x05 \x03(\tR\asymbols\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"A\n" +
	"\x12ListBrokersRequest\x12+\n" +
	"\x11include_available\x18\x01 \x01(\bR\x10includeAvailable\"\x8b\x02\n" +
	"\x13ListBrokersResponse\x12A\n" +
	"\x0frunning_brokers\x18\x01 \x03(\v2\x18.grpc_control.BrokerInfoR\x0erunningBrokers\x12E\n" +
	"\x11available_brokers\x18\x02 \x03(\v2\x18.grpc_control.BrokerInfoR\x10availableBrokers\x12#\n" +
	"\rtotal_running\x18\x03 \x01(\x05R\ftotalRunning\x12'\n" +
	"\x0ftotal_available\x18\x04 \x01(\x05R\x0etotalAvailable\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x19\n" +
	"\x17AvailableBrokersRequest\"\xa0\x01\n" +
	"\x18AvailableBrokersResponse\x12E\n" +
	"\x11available_brokers\x18\x01 \x03(\v2\x18.grpc_control.BrokerInfoR\x10availableBrokers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"N\n" +
	"\x11AddSymbolsRequest\x12\x1f\n" +
	"\vbroker_name\x18\x01 \x01(\tR\n" +
	"brokerName\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\"0\n" +
	"\x14AddSymbolsAllRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"Q\n" +
	"\x14RemoveSymbolsRequest\x12\x1f\n" +
	"\vbroker_name\x18\x01 \x01(\tR\n" +
	"brokerName\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\"3\n" +
	"\x17RemoveSymbolsAllRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\x85\x02\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12H\n" +
	"\adetails\x18\x05 \x03(\v2..grpc_control.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xb1\a\n" +
	"\x0eControlService\x12R\n" +
	"\rAddDataSource\x12\".grpc_control.AddDataSourceRequest\x1a\x1d.grpc_control.ControlResponse\x12X\n" +
	"\x10RemoveDataSource\x12%.grpc_control.RemoveDataSourceRequest\x1a\x1d.grpc_control.ControlResponse\x12N\n" +
	"\vStartBroker\x12 .grpc_control.StartBrokerRequest\x1a\x1d.grpc_control.ControlResponse\x12L\n" +
	"\n" +
	"StopBroker\x12\x1f.grpc_control.StopBrokerRequest\x1a\x1d.grpc_control.ControlResponse\x12R\n" +
	"\vListBrokers\x12 .grpc_control.ListBrokersRequest\x1a!.grpc_control.ListBrokersResponse\x12L\n" +
	"\n" +
	"AddSymbols\x12\x1f.grpc_control.AddSymbolsRequest\x1a\x1d.grpc_control.ControlResponse\x12R\n" +
	"\rAddSymbolsAll\x12\".grpc_control.AddSymbolsAllRequest\x1a\x1d.grpc_control.ControlResponse\x12R\n" +
	"\rRemoveSymbols\x12\".grpc_control.RemoveSymbolsRequest\x1a\x1d.grpc_control.ControlResponse\x12X\n" +
	"\x10RemoveSymbolsAll\x12%.grpc_control.RemoveSymbolsAllRequest\x1a\x1d.grpc_control.ControlResponse\x12[\n" +
	"\x0fGetBrokerStatus\x12$.grpc_control.GetBrokerStatusRequest\x1a\".grpc_control.BrokerStatusResponse\x12R\n" +
	"\vHealthCheck\x12 .grpc_control.HealthCheckRequest\x1a!.grpc_control.HealthCheckResponseB\x12Z\x10src/grpc_controlb\x06proto3"

var (
	file_grpc_control_proto_rawDescOnce sync.Once
	file_grpc_control_proto_rawDescData []byte
)

func file_grpc_control_proto_rawDescGZIP() []byte {
	file_grpc_control_proto_rawDescOnce.Do(func() {
		file_grpc_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_control_proto_rawDesc), len(file_grpc_control_proto_rawDesc)))
	})
	return file_grpc_control_proto_rawDescData
}

var file_grpc_control_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_grpc_control_proto_goTypes = []any{
	(*ControlResponse)(nil),          // 0: grpc_control.ControlResponse
	(*AddDataSourceRequest)(nil),     // 1: grpc_control.AddDataSourceRequest
	(*RemoveDataSourceRequest)(nil),  // 2: grpc_control.RemoveDataSourceRequest
	(*ModifyDataSourceRequest)(nil),  // 3: grpc_control.ModifyDataSourceRequest
	(*StartBrokerRequest)(nil),       // 4: grpc_control.StartBrokerRequest
	(*StopBrokerRequest)(nil),        // 5: grpc_control.StopBrokerRequest
	(*GetBrokerStatusRequest)(nil),   // 6: grpc_control.GetBrokerStatusRequest
	(*BrokerStatusResponse)(nil),     // 7: grpc_control.BrokerStatusResponse
	(*BrokerInfo)(nil),               // 8: grpc_control.BrokerInfo
	(*ListBrokersRequest)(nil),       // 9: grpc_control.ListBrokersRequest
	(*ListBrokersResponse)(nil),      // 10: grpc_control.ListBrokersResponse
	(*AvailableBrokersRequest)(nil),  // 11: grpc_control.AvailableBrokersRequest
	(*AvailableBrokersResponse)(nil), // 12: grpc_control.AvailableBrokersResponse
	(*AddSymbolsRequest)(nil),        // 13: grpc_control.AddSymbolsRequest
	(*AddSymbolsAllRequest)(nil),     // 14: grpc_control.AddSymbolsAllRequest
	(*RemoveSymbolsRequest)(nil),     // 15: grpc_control.RemoveSymbolsRequest
	(*RemoveSymbolsAllRequest)(nil),  // 16: grpc_control.RemoveSymbolsAllRequest
	(*HealthCheckRequest)(nil),       // 17: grpc_control.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 18: grpc_control.HealthCheckResponse
	nil,                              // 19: grpc_control.HealthCheckResponse.DetailsEntry
}
var file_grpc_control_proto_depIdxs = []int32{
	8,  // 0: grpc_control.ListBrokersResponse.running_brokers:type_name -> grpc_control.BrokerInfo
	8,  // 1: grpc_control.ListBrokersResponse.available_brokers:type_name -> grpc_control.BrokerInfo
	8,  // 2: grpc_control.AvailableBrokersResponse.available_brokers:type_name -> grpc_control.BrokerInfo
	19, // 3: grpc_control.HealthCheckResponse.details:type_name -> grpc_control.HealthCheckResponse.DetailsEntry
	1,  // 4: grpc_control.ControlService.AddDataSource:input_type -> grpc_control.AddDataSourceRequest
	2,  // 5: grpc_control.ControlService.RemoveDataSource:input_type -> grpc_control.RemoveDataSourceRequest
	4,  // 6: grpc_control.ControlService.StartBroker:input_type -> grpc_control.StartBrokerRequest
	5,  // 7: grpc_control.ControlService.StopBroker:input_type -> grpc_control.StopBrokerRequest
	9,  // 8: grpc_control.ControlService.ListBrokers:input_type -> grpc_control.ListBrokersRequest
	13, // 9: grpc_control.ControlService.AddSymbols:input_type -> grpc_control.AddSymbolsRequest
	14, // 10: grpc_control.ControlService.AddSymbolsAll:input_type -> grpc_control.AddSymbolsAllRequest
	15, // 11: grpc_control.ControlService.RemoveSymbols:input_type -> grpc_control.RemoveSymbolsRequest
	16, // 12: grpc_control.ControlService.RemoveSymbolsAll:input_type -> grpc_control.RemoveSymbolsAllRequest
	6,  // 13: grpc_control.ControlService.GetBrokerStatus:input_type -> grpc_control.GetBrokerStatusRequest
	17, // 14: grpc_control.ControlService.HealthCheck:input_type -> grpc_control.HealthCheckRequest
	0,  // 15: grpc_control.ControlService.AddDataSource:output_type -> grpc_control.ControlResponse
	0,  // 16: grpc_control.ControlService.RemoveDataSource:output_type -> grpc_control.ControlResponse
	0,  // 17: grpc_control.ControlService.StartBroker:output_type -> grpc_control.ControlResponse
	0,  // 18: grpc_control.ControlService.StopBroker:output_type -> grpc_control.ControlResponse
	10, // 19: grpc_control.ControlService.ListBrokers:output_type -> grpc_control.ListBrokersResponse
	0,  // 20: grpc_control.ControlService.AddSymbols:output_type -> grpc_control.ControlResponse
	0,  // 21: grpc_control.ControlService.AddSymbolsAll:output_type -> grpc_control.ControlResponse
	0,  // 22: grpc_control.ControlService.RemoveSymbols:output_type -> grpc_control.ControlResponse
	0,  // 23: grpc_control.ControlService.RemoveSymbolsAll:output_type -> grpc_control.ControlResponse
	7,  // 24: grpc_control.ControlService.GetBrokerStatus:output_type -> grpc_control.BrokerStatusResponse
	18, // 25: grpc_control.ControlService.HealthCheck:output_type -> grpc_control.HealthCheckResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_control_proto_init() }
func file_grpc_control_proto_init() {
	if File_grpc_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_control_proto_rawDesc), len(file_grpc_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_control_proto_goTypes,
		DependencyIndexes: file_grpc_control_proto_depIdxs,
		MessageInfos:      file_grpc_control_proto_msgTypes,
	}.Build()
	File_grpc_control_proto = out.File
	file_grpc_control_proto_goTypes = nil
	file_grpc_control_proto_depIdxs = nil
}
